spring:
  cloud:
    stream:
      bindings:
        # 配置自己定义的通道与哪个中间件交互
        shop_input: # ShopChannel里Input和Output的值
          destination: zhibo # 目标主题
        shop_output:
          destination: zhibo
      default-binder: kafka # 默认的binder是kafka
  kafka:
    bootstrap-servers: localhost:9092 # kafka服务地址
    consumer:
      group-id: consumer1
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      client-id: producer1








#spring:
#  application:
#    name: producer
#  cloud:
#    stream:
#      kafka:
#        binder:
          #Kafka的消息中间件服务器
#          brokers: localhost:9092
          #Zookeeper的节点，如果集群，后面加,号分隔
#          zk-nodes: localhost:2181
          #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
#          auto-create-topics: true
#      bindings:
        #这里用stream给我们提供的默认output，后面会讲到自定义output
#        output:
          #消息发往的目的地
#          destination: stream-demo
          #消息发送的格式，接收端不用指定格式，但是发送端要
#          content-type: text/plain
  # mongodb configuration
#   mongodb:
#      uri: mongodb://name:password@localhost:27017/test


