server:
  port: 8861

spring:
  application:
    name: test
#  mongodb:
#    uri: mongodb://name:password@localhost:27017/test


# input.parse
# input.field
project:
  topic: xxxxx
  verify: false
  formats:
    - type: JSON
      formula: ssss
    - type: REGEX
      formula: sssss
  fields:
    - name: assss
      type: JSON
      key-rule: ssss
      value-rule: ssss
    - name: dddd
      type: JSON
      key-rule: bbbb
      value-rule: 4444


datasource:
  hive:
    url: jdbc:hive2://119.254.118.20:10000/default
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
#      password: sixmonth
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    initial-size: 1
    min-idle: 1
    max-idle: 5
    max-active: 50
    max-wait: 10000
    time-between-eviction-runs-millis: 10000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    filters: stat

# dispatch.dataflow
dispatcher:
  dataflow:
    uri: http://192.168.1.30:9393
    repository: file://root/scdf/
    apps:
      - 1.jar
      - 2.jar
      - 3.jar
    definitions:
      test: http | log