server:
  port: 8861

spring:
  application:
    name: test
#  mongodb:
#    uri: mongodb://name:password@localhost:27017/test

# dispatch.dataflow
dispatcher:
  dataflow:
    uri: http://192.168.1.30:9393
    repository: file://root/scdf/
    apps:
      - 1.jar
      - 2.jar
      - 3.jar
    definitions:
      test: http | log