server:
  port: 8862

#spring:
#  application:
#    name: fuck
#  mongodb:
#    uri: mongodb://name:password@localhost:27017/test


# input.parse
# input.field
input:
  parse:
    formats:
      - type: JSON
        formula: ssss
      - type: REGEX
        formula: sssss
  field:
    rules:
      - name: assss
        type: JSON
        key: ssss
        value: ssss
      - name: dddd
        type: JSON
        key: bbbb
        value: 4444


